// <copyright file="Plan.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Ouroboros.Pipeline.Verification;

using System.Collections.Immutable;

/// <summary>
/// Represents an action type in the plan.
/// </summary>
public abstract record PlanAction
{
    /// <summary>
    /// Converts the action to a MeTTa atom representation.
    /// </summary>
    /// <returns>The MeTTa atom string.</returns>
    public abstract string ToMeTTaAtom();
}

/// <summary>
/// Represents a file system action.
/// </summary>
/// <param name="Operation">The operation type (e.g., "read", "write", "delete").</param>
/// <param name="Path">The target path for the operation.</param>
public sealed record FileSystemAction(string Operation, string? Path = null) : PlanAction
{
    /// <inheritdoc/>
    public override string ToMeTTaAtom() => $"(FileSystemAction \"{Operation}\")";
}

/// <summary>
/// Represents a network action.
/// </summary>
/// <param name="Operation">The operation type (e.g., "get", "post", "connect").</param>
/// <param name="Endpoint">The target endpoint for the operation.</param>
public sealed record NetworkAction(string Operation, string? Endpoint = null) : PlanAction
{
    /// <inheritdoc/>
    public override string ToMeTTaAtom() => $"(NetworkAction \"{Operation}\")";
}

/// <summary>
/// Represents a tool invocation action.
/// </summary>
/// <param name="ToolName">The name of the tool to invoke.</param>
/// <param name="Arguments">The arguments to pass to the tool.</param>
public sealed record ToolAction(string ToolName, string? Arguments = null) : PlanAction
{
    /// <inheritdoc/>
    public override string ToMeTTaAtom() => $"(ToolAction \"{ToolName}\")";
}

/// <summary>
/// Represents a plan generated by the LLM that contains a sequence of actions to execute.
/// Immutable record type following functional programming principles.
/// </summary>
public sealed record Plan
{
    private readonly ImmutableList<PlanAction> _actions;

    /// <summary>
    /// Gets the description of the plan.
    /// </summary>
    public string Description { get; }

    /// <summary>
    /// Gets the actions in this plan.
    /// </summary>
    public IReadOnlyList<PlanAction> Actions => this._actions;

    /// <summary>
    /// Initializes a new instance of the <see cref="Plan"/> class.
    /// </summary>
    /// <param name="description">The description of the plan.</param>
    /// <param name="actions">The actions in the plan.</param>
    public Plan(string description, IEnumerable<PlanAction>? actions = null)
    {
        this.Description = description ?? throw new ArgumentNullException(nameof(description));
        this._actions = actions?.ToImmutableList() ?? ImmutableList<PlanAction>.Empty;
    }

    /// <summary>
    /// Returns a new plan with an additional action.
    /// </summary>
    /// <param name="action">The action to add.</param>
    /// <returns>A new Plan with the action added.</returns>
    public Plan WithAction(PlanAction action)
    {
        ArgumentNullException.ThrowIfNull(action);
        return new Plan(this.Description, this._actions.Add(action));
    }

    /// <summary>
    /// Converts all actions in the plan to MeTTa atoms.
    /// </summary>
    /// <returns>A list of MeTTa atom strings.</returns>
    public IEnumerable<string> ToMeTTaAtoms() => this._actions.Select(a => a.ToMeTTaAtom());

    /// <summary>
    /// Converts the first action to a MeTTa atom (for single-action verification).
    /// </summary>
    /// <returns>The MeTTa atom string, or empty string if no actions.</returns>
    public string ToMeTTaAtom() => this._actions.FirstOrDefault()?.ToMeTTaAtom() ?? string.Empty;
}

/// <summary>
/// Exception thrown when a security guard rail is violated.
/// </summary>
public class SecurityException : Exception
{
    /// <summary>
    /// Gets the action that violated the guard rail.
    /// </summary>
    public string? ViolatingAction { get; }

    /// <summary>
    /// Gets the context in which the violation occurred.
    /// </summary>
    public SafeContext? Context { get; }

    /// <summary>
    /// Initializes a new instance of the <see cref="SecurityException"/> class.
    /// </summary>
    /// <param name="message">The error message.</param>
    public SecurityException(string message)
        : base(message)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="SecurityException"/> class.
    /// </summary>
    /// <param name="message">The error message.</param>
    /// <param name="violatingAction">The action that caused the violation.</param>
    /// <param name="context">The security context.</param>
    public SecurityException(string message, string violatingAction, SafeContext context)
        : base(message)
    {
        this.ViolatingAction = violatingAction;
        this.Context = context;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="SecurityException"/> class.
    /// </summary>
    /// <param name="message">The error message.</param>
    /// <param name="innerException">The inner exception.</param>
    public SecurityException(string message, Exception innerException)
        : base(message, innerException)
    {
    }
}
