// <copyright file="Plan.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace Ouroboros.Pipeline.Verification;

using System.Collections.Immutable;

/// <summary>
/// Represents a plan generated by the LLM that contains a sequence of actions to execute.
/// Immutable record type following functional programming principles.
/// </summary>
public sealed record Plan
{
    private readonly ImmutableList<PlanAction> _actions;

    /// <summary>
    /// Gets the description of the plan.
    /// </summary>
    public string Description { get; }

    /// <summary>
    /// Gets the actions in this plan.
    /// </summary>
    public IReadOnlyList<PlanAction> Actions => this._actions;

    /// <summary>
    /// Initializes a new instance of the <see cref="Plan"/> class.
    /// </summary>
    /// <param name="description">The description of the plan.</param>
    /// <param name="actions">The actions in the plan.</param>
    public Plan(string description, IEnumerable<PlanAction>? actions = null)
    {
        this.Description = description ?? throw new ArgumentNullException(nameof(description));
        this._actions = actions?.ToImmutableList() ?? ImmutableList<PlanAction>.Empty;
    }

    /// <summary>
    /// Returns a new plan with an additional action.
    /// </summary>
    /// <param name="action">The action to add.</param>
    /// <returns>A new Plan with the action added.</returns>
    public Plan WithAction(PlanAction action)
    {
        ArgumentNullException.ThrowIfNull(action);
        return new Plan(this.Description, this._actions.Add(action));
    }

    /// <summary>
    /// Converts all actions in the plan to MeTTa atoms.
    /// </summary>
    /// <returns>A list of MeTTa atom strings.</returns>
    public IEnumerable<string> ToMeTTaAtoms() => this._actions.Select(a => a.ToMeTTaAtom());

    /// <summary>
    /// Converts the first action to a MeTTa atom (for single-action verification).
    /// </summary>
    /// <returns>The MeTTa atom string, or empty string if no actions.</returns>
    public string ToMeTTaAtom() => this._actions.FirstOrDefault()?.ToMeTTaAtom() ?? string.Empty;
}