using Ouroboros.Pipeline.Learning;

namespace Ouroboros.Tests.Learning;

public class AdaptationEventTests
{
    private static AgentPerformance CreatePerformance(double quality = 0.5) =>
        AgentPerformance.Initial(Guid.NewGuid()) with
        {
            AverageResponseQuality = quality,
            TotalInteractions = 100,
        };

    [Fact]
    public void Constructor_SetsAllProperties()
    {
        // Arrange
        var id = Guid.NewGuid();
        var agentId = Guid.NewGuid();
        var before = CreatePerformance(0.5);
        var after = CreatePerformance(0.7);
        var timestamp = DateTime.UtcNow;

        // Act
        var evt = new AdaptationEvent(
            id, agentId, AdaptationEventType.StrategyChange,
            "Test adaptation", before, after, timestamp);

        // Assert
        evt.Id.Should().Be(id);
        evt.AgentId.Should().Be(agentId);
        evt.EventType.Should().Be(AdaptationEventType.StrategyChange);
        evt.Description.Should().Be("Test adaptation");
        evt.BeforeMetrics.Should().Be(before);
        evt.AfterMetrics.Should().Be(after);
        evt.Timestamp.Should().Be(timestamp);
    }

    [Fact]
    public void Create_SetsAutoGeneratedIdAndTimestamp()
    {
        // Arrange
        var agentId = Guid.NewGuid();
        var before = CreatePerformance();

        // Act
        var evt = AdaptationEvent.Create(
            agentId, AdaptationEventType.ModelUpdate, "Model updated", before);

        // Assert
        evt.Id.Should().NotBeEmpty();
        evt.AgentId.Should().Be(agentId);
        evt.EventType.Should().Be(AdaptationEventType.ModelUpdate);
        evt.Description.Should().Be("Model updated");
        evt.BeforeMetrics.Should().Be(before);
        evt.AfterMetrics.Should().BeNull();
        evt.Timestamp.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(2));
    }

    [Fact]
    public void WithAfterMetrics_SetsAfterMetrics()
    {
        // Arrange
        var evt = AdaptationEvent.Create(
            Guid.NewGuid(), AdaptationEventType.ParameterTune,
            "Tune", CreatePerformance(0.3));
        var after = CreatePerformance(0.6);

        // Act
        var updated = evt.WithAfterMetrics(after);

        // Assert
        updated.AfterMetrics.Should().Be(after);
        updated.Id.Should().Be(evt.Id);
    }

    [Fact]
    public void PerformanceDelta_WithAfterMetrics_ReturnsCorrectDelta()
    {
        // Arrange
        var before = CreatePerformance(0.3);
        var after = CreatePerformance(0.7);
        var evt = AdaptationEvent.Create(
            Guid.NewGuid(), AdaptationEventType.StrategyChange, "Test", before)
            .WithAfterMetrics(after);

        // Act
        var delta = evt.PerformanceDelta;

        // Assert
        delta.Should().NotBeNull();
        delta!.Value.Should().BeApproximately(0.4, 0.001);
    }

    [Fact]
    public void PerformanceDelta_WithoutAfterMetrics_ReturnsNull()
    {
        // Arrange
        var evt = AdaptationEvent.Create(
            Guid.NewGuid(), AdaptationEventType.ParameterTune,
            "Test", CreatePerformance());

        // Act & Assert
        evt.PerformanceDelta.Should().BeNull();
    }

    [Fact]
    public void WasBeneficial_WithPositiveDelta_ReturnsTrue()
    {
        // Arrange
        var evt = AdaptationEvent.Create(
            Guid.NewGuid(), AdaptationEventType.StrategyChange,
            "Test", CreatePerformance(0.3))
            .WithAfterMetrics(CreatePerformance(0.5));

        // Act & Assert
        evt.WasBeneficial.Should().BeTrue();
    }

    [Fact]
    public void WasBeneficial_WithNegativeDelta_ReturnsFalse()
    {
        // Arrange
        var evt = AdaptationEvent.Create(
            Guid.NewGuid(), AdaptationEventType.StrategyChange,
            "Test", CreatePerformance(0.5))
            .WithAfterMetrics(CreatePerformance(0.3));

        // Act & Assert
        evt.WasBeneficial.Should().BeFalse();
    }

    [Fact]
    public void WasBeneficial_WithoutAfterMetrics_ReturnsNull()
    {
        // Arrange
        var evt = AdaptationEvent.Create(
            Guid.NewGuid(), AdaptationEventType.ParameterTune,
            "Test", CreatePerformance());

        // Act & Assert
        evt.WasBeneficial.Should().BeNull();
    }
}
