using Ouroboros.Pipeline.Learning;

namespace Ouroboros.Tests.Learning;

public class ExperienceTests
{
    [Fact]
    public void Constructor_SetsAllProperties()
    {
        // Arrange
        var id = Guid.NewGuid();
        var metadata = ImmutableDictionary<string, object>.Empty.Add("key", "val");
        var timestamp = DateTime.UtcNow;

        // Act
        var exp = new Experience(id, "state1", "action1", 0.5, "state2", timestamp, metadata, 1.0);

        // Assert
        exp.Id.Should().Be(id);
        exp.State.Should().Be("state1");
        exp.Action.Should().Be("action1");
        exp.Reward.Should().Be(0.5);
        exp.NextState.Should().Be("state2");
        exp.Timestamp.Should().Be(timestamp);
        exp.Metadata.Should().ContainKey("key");
        exp.Priority.Should().Be(1.0);
    }

    [Fact]
    public void Create_SetsAutoGeneratedIdAndTimestamp()
    {
        // Act
        var exp = Experience.Create("s", "a", 0.5, "ns");

        // Assert
        exp.Id.Should().NotBeEmpty();
        exp.State.Should().Be("s");
        exp.Action.Should().Be("a");
        exp.Reward.Should().Be(0.5);
        exp.NextState.Should().Be("ns");
        exp.Priority.Should().Be(1.0);
        exp.Metadata.Should().BeEmpty();
        exp.Timestamp.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(2));
    }

    [Fact]
    public void Create_WithCustomPriority_UsesPriority()
    {
        // Act
        var exp = Experience.Create("s", "a", 0.5, "ns", priority: 2.5);

        // Assert
        exp.Priority.Should().Be(2.5);
    }

    [Fact]
    public void Create_WithMetadata_SetsMetadata()
    {
        // Arrange
        var metadata = ImmutableDictionary<string, object>.Empty.Add("k", "v");

        // Act
        var exp = Experience.Create("s", "a", 0.5, "ns", metadata: metadata);

        // Assert
        exp.Metadata.Should().ContainKey("k");
    }

    [Fact]
    public void WithTDErrorPriority_SetsPriorityFromTDError()
    {
        // Arrange
        var exp = Experience.Create("s", "a", 0.5, "ns");

        // Act
        var updated = exp.WithTDErrorPriority(0.8);

        // Assert
        updated.Priority.Should().BeApproximately(0.81, 0.001); // |0.8| + 0.01
    }

    [Fact]
    public void WithTDErrorPriority_WithNegativeTDError_UsesAbsoluteValue()
    {
        // Arrange
        var exp = Experience.Create("s", "a", 0.5, "ns");

        // Act
        var updated = exp.WithTDErrorPriority(-0.5);

        // Assert
        updated.Priority.Should().BeApproximately(0.51, 0.001);
    }

    [Fact]
    public void WithTDErrorPriority_WithCustomEpsilon_UsesEpsilon()
    {
        // Arrange
        var exp = Experience.Create("s", "a", 0.5, "ns");

        // Act
        var updated = exp.WithTDErrorPriority(0.3, epsilon: 0.1);

        // Assert
        updated.Priority.Should().BeApproximately(0.4, 0.001);
    }

    [Fact]
    public void WithMetadata_AddsMetadataEntry()
    {
        // Arrange
        var exp = Experience.Create("s", "a", 0.5, "ns");

        // Act
        var updated = exp.WithMetadata("source", "test");

        // Assert
        updated.Metadata.Should().ContainKey("source");
        updated.Metadata["source"].Should().Be("test");
    }

    [Fact]
    public void WithMetadata_OverwritesExistingKey()
    {
        // Arrange
        var exp = Experience.Create("s", "a", 0.5, "ns")
            .WithMetadata("key", "old");

        // Act
        var updated = exp.WithMetadata("key", "new");

        // Assert
        updated.Metadata["key"].Should().Be("new");
    }
}
