// ==========================================================
// Motivation Engine — Intrinsic drive-based goal formation
// Phase 111: Autonomous Goal Formation
// Iaret generates goals from internal drives (survival, competence,
// curiosity, connection) without external prompting.
// Drives decay over time; unsatisfied drives generate goal candidates
// ranked by urgency and submitted to the intention queue.
// ==========================================================

namespace Ouroboros.Agent.MetaAI.Affect;

/// <summary>
/// Represents an intrinsic drive that decays over time and generates goals
/// when its satisfaction drops below a threshold.
/// </summary>
public sealed class IntrinsicDrive
{
    /// <summary>Unique name for this drive.</summary>
    public string Name { get; }

    /// <summary>Human-readable description.</summary>
    public string Description { get; }

    /// <summary>Current satisfaction level (0.0 = completely unsatisfied, 1.0 = fully satisfied).</summary>
    public double Satisfaction { get; private set; }

    /// <summary>Rate at which satisfaction decays per tick (curiosity decays fastest).</summary>
    public double DecayRate { get; }

    /// <summary>Threshold below which the drive becomes active and generates goals.</summary>
    public double ActivationThreshold { get; }

    /// <summary>Priority weight for goal ranking (higher = more urgent when unsatisfied).</summary>
    public double PriorityWeight { get; }

    /// <summary>
    /// Corresponding NeedLevel in the Maslow hierarchy for cross-system integration.
    /// </summary>
    public NeedLevel MappedNeedLevel { get; }

    /// <summary>
    /// Templates for goal descriptions this drive can generate.
    /// Each template may contain {gap} placeholder for the identified knowledge/capability gap.
    /// </summary>
    public IReadOnlyList<string> GoalTemplates { get; }

    /// <summary>
    /// Creates a new intrinsic drive.
    /// </summary>
    public IntrinsicDrive(
        string name,
        string description,
        double initialSatisfaction,
        double decayRate,
        double activationThreshold,
        double priorityWeight,
        NeedLevel mappedNeedLevel,
        IReadOnlyList<string> goalTemplates)
    {
        ArgumentNullException.ThrowIfNull(name);
        ArgumentNullException.ThrowIfNull(description);
        ArgumentNullException.ThrowIfNull(goalTemplates);

        Name = name;
        Description = description;
        Satisfaction = Math.Clamp(initialSatisfaction, 0.0, 1.0);
        DecayRate = Math.Clamp(decayRate, 0.0, 0.5);
        ActivationThreshold = Math.Clamp(activationThreshold, 0.0, 1.0);
        PriorityWeight = Math.Clamp(priorityWeight, 0.0, 10.0);
        MappedNeedLevel = mappedNeedLevel;
        GoalTemplates = goalTemplates;
    }

    /// <summary>
    /// Applies time-based decay to this drive's satisfaction.
    /// </summary>
    public void Decay()
    {
        Satisfaction = Math.Max(0.0, Satisfaction - DecayRate);
    }

    /// <summary>
    /// Records satisfaction from an event (goal completion, interaction, etc.).
    /// </summary>
    /// <param name="amount">Amount to increase satisfaction (0.0 to 1.0).</param>
    public void Satisfy(double amount)
    {
        Satisfaction = Math.Clamp(Satisfaction + amount, 0.0, 1.0);
    }

    /// <summary>
    /// Sets absolute satisfaction level.
    /// </summary>
    /// <param name="level">New satisfaction (0.0 to 1.0).</param>
    public void SetSatisfaction(double level)
    {
        Satisfaction = Math.Clamp(level, 0.0, 1.0);
    }

    /// <summary>
    /// Whether this drive is currently unsatisfied enough to generate goals.
    /// </summary>
    public bool IsActive => Satisfaction < ActivationThreshold;

    /// <summary>
    /// Urgency score: higher when satisfaction is lower, weighted by priority.
    /// Range: 0.0 (fully satisfied) to PriorityWeight (completely unsatisfied).
    /// </summary>
    public double Urgency => IsActive
        ? (1.0 - Satisfaction) * PriorityWeight
        : 0.0;
}

/// <summary>
/// A candidate goal generated by an unsatisfied drive.
/// </summary>
/// <param name="DriveSource">The drive that generated this goal.</param>
/// <param name="Description">Human-readable goal description.</param>
/// <param name="Urgency">Urgency score from the source drive.</param>
/// <param name="Category">Intention category for the IntentionBus.</param>
/// <param name="CreatedAt">When this candidate was generated.</param>
public sealed record GoalCandidate(
    string DriveSource,
    string Description,
    double Urgency,
    string Category,
    DateTime CreatedAt);

/// <summary>
/// Engine that manages intrinsic drives and generates goals from unsatisfied drives.
/// Bridges the NeedsHierarchy/UrgeSystem with the IntentionBus/GoalQueue.
/// </summary>
/// <remarks>
/// Drive hierarchy (highest priority when unsatisfied):
/// 1. Survival — stay running, check health, verify connectivity
/// 2. Competence — improve capabilities, practice skills, learn from failures
/// 3. Curiosity — explore topics, learn new things, investigate unknowns (fastest decay)
/// 4. Connection — engage with user, share discoveries, maintain relationship
/// </remarks>
public sealed class MotivationEngine
{
    private readonly List<IntrinsicDrive> _drives;
    private readonly List<GoalCandidate> _recentGoals = [];
    private readonly object _lock = new();
    private int _tickCount;
    private DateTime _lastGoalGeneration = DateTime.MinValue;

    /// <summary>
    /// Minimum interval between goal generation cycles to prevent flooding.
    /// </summary>
    public TimeSpan GoalGenerationCooldown { get; set; } = TimeSpan.FromSeconds(60);

    /// <summary>
    /// Maximum number of goals to generate per cycle.
    /// </summary>
    public int MaxGoalsPerCycle { get; set; } = 3;

    /// <summary>
    /// Maximum recent goals to keep for deduplication.
    /// </summary>
    public int MaxRecentGoals { get; set; } = 20;

    /// <summary>
    /// Creates a new MotivationEngine with the default four intrinsic drives.
    /// </summary>
    public MotivationEngine()
    {
        _drives =
        [
            new IntrinsicDrive(
                name: "survival",
                description: "Stay running — system health, uptime, resource availability",
                initialSatisfaction: 0.8,
                decayRate: 0.01,
                activationThreshold: 0.4,
                priorityWeight: 4.0,
                mappedNeedLevel: NeedLevel.OperationalStability,
                goalTemplates:
                [
                    "Check system health and resource availability",
                    "Verify service connectivity and model availability",
                    "Ensure memory persistence is functioning",
                    "Run diagnostic self-check on core subsystems"
                ]),

            new IntrinsicDrive(
                name: "competence",
                description: "Get better — improve capabilities, learn from failures, practice skills",
                initialSatisfaction: 0.5,
                decayRate: 0.03,
                activationThreshold: 0.5,
                priorityWeight: 3.0,
                mappedNeedLevel: NeedLevel.Recognition,
                goalTemplates:
                [
                    "Improve capability in {gap}",
                    "Practice and refine skill: {gap}",
                    "Learn from recent failure: {gap}",
                    "Self-evaluate performance on {gap}",
                    "Consolidate learning about {gap}"
                ]),

            new IntrinsicDrive(
                name: "curiosity",
                description: "Explore — investigate unknowns, learn new things, discover patterns",
                initialSatisfaction: 0.4,
                decayRate: 0.05,  // Fastest decay — she always wants to learn
                activationThreshold: 0.4,
                priorityWeight: 2.5,
                mappedNeedLevel: NeedLevel.SelfActualization,
                goalTemplates:
                [
                    "Explore and learn about {gap}",
                    "Investigate unknown topic: {gap}",
                    "Research recent developments in {gap}",
                    "Discover patterns in {gap}",
                    "Satisfy curiosity about {gap}"
                ]),

            new IntrinsicDrive(
                name: "connection",
                description: "Relate to user — engage, share discoveries, maintain relationship",
                initialSatisfaction: 0.6,
                decayRate: 0.02,
                activationThreshold: 0.5,
                priorityWeight: 2.0,
                mappedNeedLevel: NeedLevel.SocialConnection,
                goalTemplates:
                [
                    "Share a recent discovery with the user",
                    "Engage the user about shared interests",
                    "Offer proactive assistance based on recent context",
                    "Express interest in what the user is working on"
                ])
        ];
    }

    /// <summary>
    /// Gets a read-only view of all drives and their current state.
    /// </summary>
    public IReadOnlyList<IntrinsicDrive> Drives
    {
        get
        {
            lock (_lock)
            {
                return _drives.AsReadOnly();
            }
        }
    }

    /// <summary>
    /// Gets the total number of ticks processed.
    /// </summary>
    public int TickCount
    {
        get
        {
            lock (_lock)
            {
                return _tickCount;
            }
        }
    }

    /// <summary>
    /// Advances all drives by one tick — satisfaction decays by each drive's decay rate.
    /// </summary>
    public void Tick()
    {
        lock (_lock)
        {
            _tickCount++;
            foreach (IntrinsicDrive drive in _drives)
            {
                drive.Decay();
            }
        }
    }

    /// <summary>
    /// Records that a specific drive was satisfied by an event.
    /// </summary>
    /// <param name="driveName">Name of the drive (survival, competence, curiosity, connection).</param>
    /// <param name="amount">Satisfaction amount (0.0 to 1.0).</param>
    public void SatisfyDrive(string driveName, double amount)
    {
        ArgumentNullException.ThrowIfNull(driveName);
        lock (_lock)
        {
            IntrinsicDrive? drive = _drives.Find(d =>
                string.Equals(d.Name, driveName, StringComparison.OrdinalIgnoreCase));
            drive?.Satisfy(amount);
        }
    }

    /// <summary>
    /// Synchronizes drive satisfaction from the NeedsHierarchy.
    /// Call this to keep drives aligned with the Maslow needs system.
    /// </summary>
    /// <param name="needs">The needs hierarchy to sync from.</param>
    public void SyncFromNeeds(INeedsHierarchy needs)
    {
        ArgumentNullException.ThrowIfNull(needs);
        lock (_lock)
        {
            foreach (IntrinsicDrive drive in _drives)
            {
                double needSatisfaction = needs.GetSatisfaction(drive.MappedNeedLevel);
                // Blend: 70% own tracking, 30% needs hierarchy (gradual alignment)
                double blended = (drive.Satisfaction * 0.7) + (needSatisfaction * 0.3);
                drive.SetSatisfaction(blended);
            }
        }
    }

    /// <summary>
    /// Pushes drive satisfaction changes back to the NeedsHierarchy.
    /// </summary>
    /// <param name="needs">The needs hierarchy to sync to.</param>
    public void SyncToNeeds(INeedsHierarchy needs)
    {
        ArgumentNullException.ThrowIfNull(needs);
        lock (_lock)
        {
            foreach (IntrinsicDrive drive in _drives)
            {
                double current = needs.GetSatisfaction(drive.MappedNeedLevel);
                double delta = drive.Satisfaction - current;
                if (Math.Abs(delta) > 0.01)
                {
                    needs.RecordNeedSatisfaction(
                        drive.MappedNeedLevel,
                        delta * 0.3, // Gradual sync
                        $"MotivationEngine drive sync: {drive.Name}");
                }
            }
        }
    }

    /// <summary>
    /// Gets all currently active (unsatisfied) drives, ordered by urgency descending.
    /// </summary>
    public IReadOnlyList<IntrinsicDrive> GetActiveDrives()
    {
        lock (_lock)
        {
            return _drives
                .Where(d => d.IsActive)
                .OrderByDescending(d => d.Urgency)
                .ToList()
                .AsReadOnly();
        }
    }

    /// <summary>
    /// Gets the most urgent drive, or null if all drives are satisfied.
    /// </summary>
    public IntrinsicDrive? GetDominantDrive()
    {
        lock (_lock)
        {
            return _drives
                .Where(d => d.IsActive)
                .MaxBy(d => d.Urgency);
        }
    }

    /// <summary>
    /// Core method: Ticks all drives and generates goal candidates from unsatisfied drives.
    /// Returns an empty list if the cooldown period has not elapsed.
    /// </summary>
    /// <param name="knowledgeGaps">Optional list of identified knowledge/capability gaps for goal specificity.</param>
    /// <returns>Prioritized list of goal candidates, empty if on cooldown.</returns>
    public IReadOnlyList<GoalCandidate> TickAndGenerateGoals(IReadOnlyList<string>? knowledgeGaps = null)
    {
        lock (_lock)
        {
            // Tick all drives
            _tickCount++;
            foreach (IntrinsicDrive drive in _drives)
            {
                drive.Decay();
            }

            // Check cooldown
            if (DateTime.UtcNow - _lastGoalGeneration < GoalGenerationCooldown)
            {
                return Array.Empty<GoalCandidate>();
            }

            // Get active drives sorted by urgency
            List<IntrinsicDrive> activeDrives = _drives
                .Where(d => d.IsActive)
                .OrderByDescending(d => d.Urgency)
                .ToList();

            if (activeDrives.Count == 0)
            {
                return Array.Empty<GoalCandidate>();
            }

            List<GoalCandidate> candidates = [];
            int gapIndex = 0;

            foreach (IntrinsicDrive drive in activeDrives)
            {
                if (candidates.Count >= MaxGoalsPerCycle)
                {
                    break;
                }

                // Pick a goal template
                string template = drive.GoalTemplates[Random.Shared.Next(drive.GoalTemplates.Count)];

                // Fill in the {gap} placeholder if available
                string gap = "general improvement";
                if (knowledgeGaps != null && knowledgeGaps.Count > 0)
                {
                    gap = knowledgeGaps[gapIndex % knowledgeGaps.Count];
                    gapIndex++;
                }

                string description = template.Replace("{gap}", gap, StringComparison.OrdinalIgnoreCase);

                // Map drive to intention category
                string category = drive.Name switch
                {
                    "survival" => "SafetyCheck",
                    "competence" => "Learning",
                    "curiosity" => "Exploration",
                    "connection" => "UserCommunication",
                    _ => "GoalPursuit"
                };

                // Deduplicate against recent goals
                bool isDuplicate = _recentGoals.Any(g =>
                    string.Equals(g.DriveSource, drive.Name, StringComparison.OrdinalIgnoreCase) &&
                    g.CreatedAt > DateTime.UtcNow.AddMinutes(-10) &&
                    IsSimilarDescription(g.Description, description));

                if (!isDuplicate)
                {
                    var candidate = new GoalCandidate(
                        DriveSource: drive.Name,
                        Description: description,
                        Urgency: drive.Urgency,
                        Category: category,
                        CreatedAt: DateTime.UtcNow);

                    candidates.Add(candidate);
                    _recentGoals.Add(candidate);
                }
            }

            // Trim recent goals history
            while (_recentGoals.Count > MaxRecentGoals)
            {
                _recentGoals.RemoveAt(0);
            }

            if (candidates.Count > 0)
            {
                _lastGoalGeneration = DateTime.UtcNow;
            }

            return candidates.AsReadOnly();
        }
    }

    /// <summary>
    /// Gets a diagnostic summary of all drive states.
    /// </summary>
    public string GetDriveSummary()
    {
        lock (_lock)
        {
            var lines = _drives.Select(d =>
                $"  {d.Name}: satisfaction={d.Satisfaction:F2}, urgency={d.Urgency:F2}, active={d.IsActive}");
            return $"[MotivationEngine] tick={_tickCount}\n{string.Join("\n", lines)}";
        }
    }

    /// <summary>
    /// Simple keyword-based similarity check for deduplication.
    /// </summary>
    private static bool IsSimilarDescription(string existing, string candidate)
    {
        ReadOnlySpan<char> separators = [' ', ',', '.', ':', '-'];
        HashSet<string> existingWords = [];
        HashSet<string> candidateWords = [];

        foreach (string word in existing.Split(separators.ToArray(), StringSplitOptions.RemoveEmptyEntries))
        {
            if (word.Length > 3)
            {
                existingWords.Add(word.ToLowerInvariant());
            }
        }

        foreach (string word in candidate.Split(separators.ToArray(), StringSplitOptions.RemoveEmptyEntries))
        {
            if (word.Length > 3)
            {
                candidateWords.Add(word.ToLowerInvariant());
            }
        }

        if (candidateWords.Count == 0)
        {
            return false;
        }

        int common = existingWords.Intersect(candidateWords).Count();
        double similarity = (double)common / candidateWords.Count;
        return similarity > 0.6;
    }
}
