using Ouroboros.Pipeline.Council;

namespace Ouroboros.Tests.Council;

[Trait("Category", "Unit")]
public class AgentContributionTests
{
    [Fact]
    public void Constructor_WithRequiredParameters_SetsProperties()
    {
        // Arrange & Act
        var contribution = new AgentContribution("TestAgent", "Test content");

        // Assert
        contribution.AgentName.Should().Be("TestAgent");
        contribution.Content.Should().Be("Test content");
        contribution.TargetAgent.Should().BeNull();
        contribution.ReferencedContributions.Should().BeNull();
    }

    [Fact]
    public void Constructor_WithAllParameters_SetsAllProperties()
    {
        // Arrange
        var referencedIds = new List<Guid> { Guid.NewGuid(), Guid.NewGuid() };

        // Act
        var contribution = new AgentContribution(
            "TestAgent",
            "Test content",
            "TargetAgent",
            referencedIds);

        // Assert
        contribution.AgentName.Should().Be("TestAgent");
        contribution.Content.Should().Be("Test content");
        contribution.TargetAgent.Should().Be("TargetAgent");
        contribution.ReferencedContributions.Should().BeEquivalentTo(referencedIds);
    }

    [Fact]
    public void Id_IsAutoGenerated_AndUnique()
    {
        // Act
        var contribution1 = new AgentContribution("Agent1", "Content1");
        var contribution2 = new AgentContribution("Agent2", "Content2");

        // Assert
        contribution1.Id.Should().NotBe(Guid.Empty);
        contribution2.Id.Should().NotBe(Guid.Empty);
        contribution1.Id.Should().NotBe(contribution2.Id);
    }

    [Fact]
    public void Id_CanBeSetViaInit()
    {
        // Arrange
        var customId = Guid.NewGuid();

        // Act
        var contribution = new AgentContribution("TestAgent", "Content") { Id = customId };

        // Assert
        contribution.Id.Should().Be(customId);
    }

    [Fact]
    public void RecordEquality_WithSameValues_AreEqual()
    {
        // Arrange
        var id = Guid.NewGuid();

        // Act
        var contribution1 = new AgentContribution("Agent", "Content") { Id = id };
        var contribution2 = new AgentContribution("Agent", "Content") { Id = id };

        // Assert
        contribution1.Should().Be(contribution2);
    }

    [Fact]
    public void RecordEquality_WithDifferentIds_AreNotEqual()
    {
        // Act
        var contribution1 = new AgentContribution("Agent", "Content");
        var contribution2 = new AgentContribution("Agent", "Content");

        // Assert — auto-generated Ids differ
        contribution1.Should().NotBe(contribution2);
    }

    [Fact]
    public void With_CreatesModifiedCopy()
    {
        // Arrange
        var original = new AgentContribution("Agent", "Original content");

        // Act
        var modified = original with { Content = "Modified content" };

        // Assert
        modified.AgentName.Should().Be("Agent");
        modified.Content.Should().Be("Modified content");
        modified.Id.Should().Be(original.Id);
    }
}
