namespace Ouroboros.Tests.Pipeline.Council;

using Ouroboros.Pipeline.Council;

[Trait("Category", "Unit")]
public class AgentContributionTests
{
    [Fact]
    public void Constructor_SetsRequiredProperties()
    {
        var contribution = new AgentContribution("Agent1", "Content here");

        contribution.AgentName.Should().Be("Agent1");
        contribution.Content.Should().Be("Content here");
        contribution.TargetAgent.Should().BeNull();
        contribution.ReferencedContributions.Should().BeNull();
    }

    [Fact]
    public void Constructor_WithOptionalParams_SetsAll()
    {
        var refs = new List<Guid> { Guid.NewGuid() };
        var contribution = new AgentContribution("Agent1", "Content", "Agent2", refs);

        contribution.TargetAgent.Should().Be("Agent2");
        contribution.ReferencedContributions.Should().BeSameAs(refs);
    }

    [Fact]
    public void Id_IsAutoGenerated()
    {
        var c1 = new AgentContribution("A", "B");
        var c2 = new AgentContribution("A", "B");

        c1.Id.Should().NotBe(Guid.Empty);
        c2.Id.Should().NotBe(Guid.Empty);
        c1.Id.Should().NotBe(c2.Id);
    }
}
