using Ouroboros.Abstractions;

namespace Ouroboros.Pipeline.Metacognition;

/// <summary>
/// Represents an alert generated by cognitive monitoring.
/// Alerts are triggered when monitored metrics exceed defined thresholds or patterns are detected.
/// </summary>
/// <param name="Id">Unique identifier for this alert.</param>
/// <param name="AlertType">The type/category of the alert.</param>
/// <param name="Message">Human-readable message describing the alert.</param>
/// <param name="TriggeringEvents">The cognitive events that triggered this alert.</param>
/// <param name="RecommendedAction">Suggested action to address the alert.</param>
/// <param name="Priority">Priority level from 1 (lowest) to 10 (highest).</param>
/// <param name="Timestamp">When the alert was generated.</param>
public sealed record MonitoringAlert(
    Guid Id,
    string AlertType,
    string Message,
    ImmutableList<CognitiveEvent> TriggeringEvents,
    string RecommendedAction,
    int Priority,
    DateTime Timestamp)
{
    /// <summary>
    /// Creates a new high-priority alert.
    /// </summary>
    /// <param name="alertType">The type of alert.</param>
    /// <param name="message">The alert message.</param>
    /// <param name="triggeringEvents">Events that triggered the alert.</param>
    /// <param name="recommendedAction">Recommended action to take.</param>
    /// <returns>A new high-priority MonitoringAlert.</returns>
    public static MonitoringAlert HighPriority(
        string alertType,
        string message,
        IEnumerable<CognitiveEvent> triggeringEvents,
        string recommendedAction) => new(
        Id: Guid.NewGuid(),
        AlertType: alertType,
        Message: message,
        TriggeringEvents: triggeringEvents.ToImmutableList(),
        RecommendedAction: recommendedAction,
        Priority: 8,
        Timestamp: DateTime.UtcNow);

    /// <summary>
    /// Creates a new medium-priority alert.
    /// </summary>
    /// <param name="alertType">The type of alert.</param>
    /// <param name="message">The alert message.</param>
    /// <param name="triggeringEvents">Events that triggered the alert.</param>
    /// <param name="recommendedAction">Recommended action to take.</param>
    /// <returns>A new medium-priority MonitoringAlert.</returns>
    public static MonitoringAlert MediumPriority(
        string alertType,
        string message,
        IEnumerable<CognitiveEvent> triggeringEvents,
        string recommendedAction) => new(
        Id: Guid.NewGuid(),
        AlertType: alertType,
        Message: message,
        TriggeringEvents: triggeringEvents.ToImmutableList(),
        RecommendedAction: recommendedAction,
        Priority: 5,
        Timestamp: DateTime.UtcNow);

    /// <summary>
    /// Creates a new low-priority alert.
    /// </summary>
    /// <param name="alertType">The type of alert.</param>
    /// <param name="message">The alert message.</param>
    /// <param name="triggeringEvents">Events that triggered the alert.</param>
    /// <param name="recommendedAction">Recommended action to take.</param>
    /// <returns>A new low-priority MonitoringAlert.</returns>
    public static MonitoringAlert LowPriority(
        string alertType,
        string message,
        IEnumerable<CognitiveEvent> triggeringEvents,
        string recommendedAction) => new(
        Id: Guid.NewGuid(),
        AlertType: alertType,
        Message: message,
        TriggeringEvents: triggeringEvents.ToImmutableList(),
        RecommendedAction: recommendedAction,
        Priority: 2,
        Timestamp: DateTime.UtcNow);

    /// <summary>
    /// Validates the alert priority is within valid range.
    /// </summary>
    /// <returns>A Result indicating validity or validation error.</returns>
    public Result<Unit, string> Validate()
    {
        if (Priority < 1 || Priority > 10)
        {
            return Result<Unit, string>.Failure($"Priority must be in [1, 10], got {Priority}.");
        }

        if (string.IsNullOrWhiteSpace(AlertType))
        {
            return Result<Unit, string>.Failure("AlertType cannot be empty.");
        }

        if (string.IsNullOrWhiteSpace(Message))
        {
            return Result<Unit, string>.Failure("Message cannot be empty.");
        }

        return Result<Unit, string>.Success(Unit.Value);
    }
}